### ISSUE TITLE
Move Todos

### ISSUE THREAD

**Issue by forrestolivo** [basecamp/bcx-api#132]
I need to be able to move tasks between todo lists. I can easily delete and then recreate them, but this doesn't preserve comment threads so it isn't really a viable solution. It would be great if we could use the API to add todos to the queue to be moved.

**Comment by matijakregar** [comment]
Actually it is possible to move todos between lists. Just update the todo with a different todo list id. Has to be a list within the same project though.

**Comment by mildred** [comment]
:+1: 
Internally, we use todo lists to keep items, and move the items across different lists like a kanban. Being able to move todo items would be very nice in the API.

**Comment by rosa** [comment]
Sorry about this one, @vins31! We won't be adding any new features to the BCX API in the future, so I'm closing this one. We should have updated this much sooner.
