### ISSUE TITLE
Convert mask for your Timestamp in Oracle

### ISSUE THREAD

**Issue by ragrawa** [basecamp/bcx-api#173]
Hi
To insert your timestamp string to Java Oracle "DATE", can you suggest a TO_TIMESTAMP(?, ?) for your JSON String?

**Comment by jeremy** [comment]
Timestamps are ISO 8601 format. It's probably simplest to parse it in Java first, then format it however you like when inserting into your date column.

If you'd like to insert it into your column directly, you'll need to build a TO_TIMESTAMP_TZ format string (ISO 8601 format includes time zone offset) and test it out. Check out http://stackoverflow.com/questions/8654292/how-to-convert-1985-02-07t000000-000z-iso8601-to-a-date-value-in-oracle for some examples.

Parsing in Java first is a better route than hardcoding a format string, though!
