### ISSUE TITLE
Getting all todos at once

### ISSUE THREAD

**Issue by matijakregar** [basecamp/bcx-api#176]
I tried getting all to-dos with GET /todos.json request and i get some to-dos, but not all of them. Getting todo lists first (GET /todolists.json) and then fetching all to-dos by list (GET /projects/1/todolists/1/todos.json) returns a different set of to-dos. Not to mention a much higher number of requests.

**Comment by eileencodes** [comment]
@matijakregar /todos.json return all to-dos that are not trashed but they are paginated so you see 10 at a time. You need to request page 2 to get the next 10 and so on. 

Thanks for using the Basecamp API! :smile:

**Comment by IgorBurakov** [comment]
Isn't the page size is 50 items?

**Comment by eileencodes** [comment]
@IgorBurakov yes sorry I misspoke it's 50.

**Comment by matijakregar** [comment]
How about documenting this feature? 
And also enabling the /remaining.json, /completed.json etc.

**Comment by matijakregar** [comment]
Otherwise, thanks for your answer ...

**Comment by eileencodes** [comment]
The only thing not documented is that these are paged. Remaining and completed are enabled and documented.

From https://github.com/basecamp/bcx-api/blob/master/sections/todos.md. 

Per Project:

GET /projects/1/todos.json shows a list of all to-dos for this project; completed and remaining.
GET /projects/1/todos/completed.json shows a list of all completed to-dos for this project.
GET /projects/1/todos/remaining.json shows a list of all remaining/active to-dos for this project.
GET /projects/1/todos.json?due_since=2014-07-10 will return all the to-dos due after the date specified.
Per To-do List:

GET /projects/1/todolists/1/todos.json shows a list of all to-dos for this to-do list; completed and remaining.
GET /projects/1/todolists/1/todos/completed.json shows a list of all completed to-dos for this to-do list.
GET /projects/1/todolists/1/todos/remaining.json shows a list of all remaining to-dos for this to-do list.
GET /projects/1/todolists/1/todos/trashed.json shows a list of all trashed to-dos for this to-do list.

**Comment by matijakregar** [comment]
I saw that, but i meant GET /todos.json per account, not per project or per to-do list. All account to-dos are not documented at all but /todos.json works with paging, /remaining.json doesn't.

My initial question/request was regarding all account to-dos (specifically /todos/remaining.json) which would (in my case) significantly reduce the number of requests on your server.

**Comment by eileencodes** [comment]
@matijakregar it may reduce the number of requests you need to make but it would still be a hit to our servers to allow a get of all todos at once. We don't plan on implementing that at this time. For now we only allow per todolist or per project.

**Comment by matijakregar** [comment]
Well, actually you do allow to-dos per account. It's just not documented and the filters are not working ;)

**Comment by eileencodes** [comment]
Sometimes developers are wrong and that's ok, please be nice about it. "Well actually..." is patronizing.

I had forgotten about the global todo endpoint and was looking at the code for the todo index which only allows todos via project or todolist. At this time we don't plan on implementing global for remaining or completed todos.

**Comment by bojan** [comment]
@eileencodes There isn't a **single** mention of the paging parameter in any of the todo related documents. Could you please at least review the docs?

**Comment by jimmackenzie** [comment]
@bojan We do mention pagination here: https://github.com/basecamp/bcx-api#pagination, as it applies across a number of endpoints. Perhaps we could try repeating it in each of the documents.  We'll talk it over.

**Comment by bojan** [comment]
Thanks @jimmackenzie for the quick reply! Maybe you can just add a list of paginated entities instead of "most" :smile:
