### ISSUE TITLE
Image as attachement

### ISSUE THREAD

**Issue by faxdata** [basecamp/bcx-api#178]
Trying to upload attachements, but image files seems to get corrupted once in Basecamp. They get uploaded and attached to my todos and everything looks OK, but they are not recognized as image files when trying to open them in Basecamp. Other file types(pdf, xlsx, docx, csv) working fine with my code.

Using Python Requests:

my_file = {'file': open(os.path.join(app.config['UPLOAD_FOLDER'], f['name'])).read()}
			headers = {'Content-type': f['type']}
			r = requests.post("https://basecamp.com/"+BASECAMP_ID+"/api/v1/attachments.json", files=my_file, auth=HTTPBasicAuth(USERNAME,PW), headers=headers)

**Comment by georgeclaghorn** [comment]
Hi @faxdata! Can you share examples of the following for the image attachments you're having trouble with:

* the Content-Type header values you're sending with image attachments
* the names you're giving image attachments when you attach them to something

**Comment by faxdata** [comment]
Hi @georgeclaghorn !

For a jpg it would look something like this:
headers = {'Content-Type': 'image/jpeg'}
And nothing fishy about the filenames, just legit characters, like: "foo.jpg"

**Comment by jimmackenzie** [comment]
Hey @faxdata, thanks for that.  Could you send over some of the urls of some freshly-uploaded images using https://basecamp.com/support? We can take a look at the requests and see what is occurring.

_Adding the IP address and timestamp of your request would be super helpful too_

**Comment by faxdata** [comment]
Thanks @georgeclaghorn ! Additional information sent to Basecamp support.

**Comment by faxdata** [comment]
Thanks very much for your help @jimmackenzie and @georgeclaghorn ! 
My mistake, I did not send the binary data properly from my side.
