### ISSUE TITLE
Clarify which collection endpoints are paginated

### ISSUE THREAD

**Issue by alexandrecormier** [basecamp/bcx-api#179]
@jimmackenzie mentioned it in #176, but I'd like a follow up and I think it's worth having a separate issue.

It would be nice if the documentation specified clearly which endpoints are paginated and which ones are not. It says most are, and then for some endpoints it's stated that they are, but for a lot of them it's unclear. None of those mention pagination : calendars, documents, forwards, groups/subgroups, people, projects/templates, stars, todos, todolists.

I suggest making it explicit in every collection endpoint's document, whether it's paginated or not.

Thanks for your time!

**Comment by eileencodes** [comment]
Hi @alexandrecormier thanks for the suggestion! We'll take it into consideration and let you know when the changes are added. 

By the way, if you're interested, we do accept pull requests to the documentation if you ever find something you think should be changed :smile:

**Comment by danielpquinn** [comment]
This would be very helpful. I would also like documentation that clarifies whether unpaginated endpoints contain a complete list of results for that collection.
