### ISSUE TITLE
How to restore todo?

### ISSUE THREAD

**Issue by dvddmt** [basecamp/bcx-api#180]
Is there something like POST /api/v1/projects/7544784/todos/184655268/restore.json to restore trashed todos?
I have tried to update todo to change ```"trashed": true``` flag, but it didn't solve my problem. I need to restore about 11000 todo items which were accidentally trashed. How can I achieve that?

**Comment by eileencodes** [comment]
Hi @dvddmt. Apologies for the late reply, I didn't see your question.

We currently don't have an endpoint for restoring trashed todos. Sorry about that! If you trashed the todo as part of a list you can restore the entire list rather than individual todos.
