### ISSUE TITLE
Getting Blank content in file

### ISSUE THREAD

**Issue by Gajendracis** [basecamp/bcx-api#189]
Hi,

I am making the following request but I am getting blank {} as in file content inside file. I dont know please let me know where I am wrong

curl -X POST "https://basecamp.com/{account_id}/api/v1/projects/{project_id}/uploads.json"  -H "Authorization: Bearer {access_token}" -H "User-Agent: {app_name}" -H "Content-Type: application/json" -d '{"content":"For testinfg only ..", "attachments":[{"token":"c9187714b130d4acaf520e0b2231c68c0010", "name": "NewFile1qw11.txt"}]}'

**Comment by eileencodes** [comment]
Hi @Gajendracis - apologies for the late reply I missed your request.

Are you still having trouble with this? If you are let me know and I'll reopen.

**Comment by Gajendracis** [comment]
yes I am still have the same issue.

**Comment by Gajendracis** [comment]
I dont know Why I am unable to get content in file.

**Comment by eileencodes** [comment]
Can you clarify for me what you're getting back? Do you mean that you're only getting an empty hash or that a part of response that should have the file value is empty? Or do you mean that when you look at the uploaded file it's empty? Can you to paste your response here (of course removing any sensitive data)?
