### ISSUE TITLE
How to securely use OAuth2.0 in Chrome extension

### ISSUE THREAD

**Issue by jormaechea** [basecamp/bcx-api#190]
I'm developing a chrome extension that authenticates against Basecamp.

I've used [Chrome Identity API](https://developer.chrome.com/apps/identity) and following [this steps](https://developer.chrome.com/apps/app_identity#non).

I managed to get the Authorization Page, and when the user accepts I get the verification code as explained in your [authentication docu](https://github.com/basecamp/api/blob/master/sections/authentication.md#oauth-2-from-scratch).

My problem starts when I reach step 4 of your documentation:
> Your app makes a backchannel request to trade the verification code for an access token. We authenticate your app and issue an access token:

    POST https://launchpad.37signals.com/authorization/token?type=web_server&client_id=your-client-id&redirect_uri=your-redirect-uri&client_secret=your-client-secret&code=verification-code

As I'm in a Chrome Extension, I have no server-side, so I'm supposed to **post my client secret in the code**, which is accessible by anyone. This is a huge potential security issue that may compromise my app and every user's personal (and bussiness) data.

Is there any way to authenticate without sharing my app client secret with everyone?
If not, what could be the solution to this issue?

Thanks in advance.

**Comment by jormaechea** [comment]
Sorry, just changed 
    type=web_server
to
    type=user_agent
in the authorization request and got the token.

I'm closing this issue.

**Comment by jeremy** [comment]
:metal: 

Keeping secrets in extensions and mobile apps is a lost cause. The OAuth 2 spec didn't anticipate this well (IMO).
