### ISSUE TITLE
View history of a TODO item moved across lists

### ISSUE THREAD

**Issue by mildred** [basecamp/bcx-api#192]
In the basecamp web interface, when we move the TODO item from one list to another, we can see a message like:

> Firstname LASTNAME moved the to-do from '&lt;old todo list&gt;' to '&lt;current todo list&gt;'

Having access to this information from the API is very important for us, as we move TODO items when important things happen. And we would like to generate a recap from this. I would suggest a `history` key containing the history for the item (being moved, due date changed, title changed, assignee changed)

**Comment by eileencodes** [comment]
Hi @mildred! The events api endpoint (https://github.com/basecamp/bcx-api/blob/master/sections/events.md) should give you what you need. It will give you all events per project, including what lists/todos were moved. Then on your end you could filter by the eventable type and id of the moved list or item.

**Comment by mildred** [comment]
Thank you
