### ISSUE TITLE
Basecamp 3 Automatic Check-ins API?

### ISSUE THREAD

**Issue by chadalderson** [basecamp/bcx-api#198]
I don't see an obvious way to integrate w/ the Check-ins section (http://d.pr/i/1ag1U) of Basecamp 3 via API. Is there one?

**Comment by eileencodes** [comment]
The BC3 API isn't currently public. This API documentation is for Basecamp 2. We will update this issue https://github.com/basecamp/bcx-api/issues/196 when we make the Basecamp 3 API public.

**Comment by chadalderson** [comment]
Thanks @eileencodes for the quick response. Appreciate the clarification. Yes it would be great to be able to connect 3rd party apps in the Check-ins section.
