### ISSUE TITLE
401 Unknown Basecamp ID

### ISSUE THREAD

**Issue by dzafel** [basecamp/bcx-api#199]
Hey, I'm having some problems with API since yesterday, when I try to refresh token I get `401 Unknown Basecamp ID.` error. I can't find any information in your docs about this error. Did you guys change anything lately? I used the code for refreshing tokens for a long time now and it stopped working yesterday. What is "Basecamp ID"? I have many customers in my webapp and they all get the same error.

**Comment by georgeclaghorn** [comment]
Hi @dzafel! Sorry for the trouble. Could you shoot an email to support@basecamp.com? They'll be able to help you out.
