### ISSUE TITLE
Retrieving comments by to-do

### ISSUE THREAD

**Issue by andrewevansmith** [basecamp/bcx-api#205]
Reading through the documentation, it's unclear to me how to get comments by to-do.  I've tried to retrieve associated topics by to-do, but haven't had any luck.

Per the documentation:

> Comments are included on the topics directly. So to see all comments for a message, you'd just GET that message and they're included and look like this:

How do you GET the message for a given to-do?  Which identifier do you use?

**Comment by andrewevansmith** [comment]
For more clarity, I've got the full list of active to-dos, I'm trying to get a list of all comments this week on each to-do.

**Comment by georgeclaghorn** [comment]
To get the comments on an individual to-do, you can [request the to-do itself](https://github.com/basecamp/bcx-api/blob/master/sections/todos.md#get-to-do). The comments are included like so:

```
{
  "id": 1,
  "todolist_id": 1000,
  "position": 1,
  "content": "Test it",
  ...
  "comments": [
    {
      "id": 1028592764,
      "content": "Yeah, really, welcome!",
      "created_at": "2012-03-22T16:56:48-05:00",
      "updated_at": "2012-03-22T16:56:48-05:00",
      ...
    },
    ...
  ]
}
```

Sorry this isn't clear from the docs. Hope that helps!

**Comment by skarmani2002** [comment]
After fetching the to-do itself there is no comments in list,The list only  shows comments count in json.is there is any way to fetch all comment with todos ?

**Comment by georgeclaghorn** [comment]
@skarmani2002: Weird! Can you send an email to support@basecamp.com with the URL for a specific to-do that isn't including its comments so we can investigate?

**Comment by skarmani2002** [comment]
Im using following api call 
 https://github.com/basecamp/bcx-api/blob/master/sections/todos.md#get-to-do
 Even in documentation of this page comments are missing .

**Comment by georgeclaghorn** [comment]
Yeah, the docs are outdated. I'll update them shortly. Again, can you email us the exact URL you're requesting?

**Comment by skarmani2002** [comment]
@georgeclaghorn   Yes i sent an email on  support@basecamp.com.
