### ISSUE TITLE
Webhook triggering isssue

### ISSUE THREAD

**Issue by harisheidiko** [basecamp/bcx-api#206]
Hi,
   I am integrating basecamp with my application.I post a message in message board,then i got a message.when 
I post a message in campfire/chat room.But I didn't get message.shall we have webhook option for campfire or not.I hope you will resolve this issue.Quick help needed.Thanks in advance

**Comment by jeremy** [comment]
Hi @harisheidiko, Basecamp 3 chat is too high-volume for webhooks. Check out the [Chatbot API](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots) instead.

(Note, this is for the Basecamp 2 API. Check out the Basecamp 3 API at https://github.com/basecamp/bc3-api.)

**Comment by harisheidiko** [comment]
Hi Jeremy Daer,

     Thanks for your quick reply.And I have one more issue with the event
"ScheduleEntry".I had created web hook for all the events,then I got
messages for those events except schedule::entry event. Thanks in advance

On Fri, Sep 30, 2016 at 10:35 PM, Jeremy Daer <notifications@github.com>
wrote:
>
> Hi @harisheidiko, Basecamp 3 chat is too high-volume for webhooks. Check
out the Chatbot API instead.
>
> (Note, this is for the Basecamp 2 API. Check out the Basecamp 3 API at
https://github.com/basecamp/bc3-api.)
