### ISSUE TITLE
Basecamp 3 API - Identifying Archived Projects

### ISSUE THREAD

**Issue by JoelGross** [basecamp/bcx-api#211]
Documentation here https://github.com/basecamp/bcx-api/blob/master/sections/projects.md indicates I that when I GET /projects.json I will get a list of all active projects including the following details:
{
    "id": 605816632,
    "name": "BCX",
    "description": "The Next Generation",
    "updated_at": "2012-03-23T13:55:43-05:00",
    "url": "https://basecamp.com/999999999/api/v1/projects/605816632.json",
    "app_url": "https://basecamp.com/999999999/projects/605816632",
    "template": false,
    "archived": false,
    "starred": true,
    "trashed": false,
    "draft":false,
    "is_client_project": false,
    "color": "3185c5"
  }

However, the response I actually get is in the attached image
![image](https://cloud.githubusercontent.com/assets/1836213/21863778/a8349822-d7f3-11e6-98c8-320bead7221f.png)

The issue is that I can't tell programmatically which projects are archived. That means I am showing archived projects in my application. How can I tell which projects have been archived so I can make sure they are not included?

**Comment by jeremy** [comment]
Looks like you're using the Basecamp 3 API but referencing Basecamp 2 API docs.

Here's the response you should expect in Basecamp 3: https://github.com/basecamp/bc3-api/blob/master/sections/basecamps.md#get-basecamps
