### ISSUE TITLE
More reliable way to track rate limits

### ISSUE THREAD

**Issue by urkle** [basecamp/bcx-api#212]
Currently we are utilizing the X-RateLimit header that is sent back with each request to manage rate limits in our API usage.  However that header provides a "until" as an ISO8601 timestamp of when the rate limit resets..  This is not very useful as it assumes that your system and our system are perfectly in sync with each other.  A better value would be a delta # of seconds.  e.g.
```
X-RateLimit: {"name":"API","period":10,"limit":50,"remaining":0,"until":"2016-01-01T12:00:20Z","until_seconds":3}
```

That way I do not need to have perfect time synchronization with your servers, as you provide a rounded-up number of seconds until the rate period resets.  (thus I can easily sleep on that and not worry about hitting a rate limit)

**Comment by jeremy** [comment]
Good point. Are you seeing significant clock skew?

We recommend waiting for the rate limit period rather than trying to exactly gauge the time remaining.

**Comment by urkle** [comment]
but if I'm 5 seconds into the period, why would I wait an additional 10 seconds when only 5 would do?

We implemented handling of "sleeping" in our sync loop since some of our customers are frequently hitting the rate limit.. (~ 30-40 times every 5 minutes, probably because they couldn't get through the initial sync to get on the delta).    now after putting this change in production that reduced to about 15/5 minutes..   and we are seeing "sleep" times of upwards of 2 minutes per 5 minutes!

**Comment by raulpopadineti** [comment]
@jeremy last time when we talked about the rate limit, you guys said that if it's an exceptional case, you'll be able to loosen it. /cc @urkle
