### ISSUE TITLE
Attachments: How to attach and upload?

### ISSUE THREAD

**Issue by GaryLBaird** [basecamp/bcx-api#216]
# Attachments: How to attach and upload files using the API?
I'm a little new to API's so perhaps I am struggling with making them work.

**1. How do I generate the token and get this back?**
something like:
```
{
  "token": "4f71ea23-134660425d1818169ecfdbaa43cfc07f4e33ef4c"
}
```

**2. How do add the token and upload the file the the project?**
something like:
```
{
  "content": "Here is some text file.",
  "attachments": [
    {
      "token": "4f71ea23-134660425d1818169ecfdbaa43cfc07f4e33ef4c",
      "name": "sometestfile.txt"
    }
  ],
  "subscribers": [7]
}
```

## I think I am doing some things correctly because the following work for me using ARC:
```
accept: application/json
authorization: Basic ({MyBase64Hash}
Content-Type: application/json
User-Agent: ({MyUserName}@{MyCompany.com})
```

https://basecamp.com/{MyCompanyID}/api/v1/projects.json
Results are as expected in JSON.
https://basecamp.com/{MyCompanyID}/api/v1/attachments.json
Results are as expected in JSON.
https://basecamp.com/{MyCompanyID}/api/v1/projects/{MyProjectID}/accesses.json
Results are as expected in JSON.
https://basecamp.com/{MyCompanyID}/api/v1/projects/{MyProjectID}/uploads.json
Results are as expected in JSON.

**Comment by rosa** [comment]
Hey @GaryLBaird! Let me try to help 😄 We have [some documentation](https://github.com/basecamp/bcx-api/blob/master/sections/attachments.md#attachments) on how to create attachments. Basically, you need to do two things:

1. Send a `POST` request to `/attachments.json` (that is, `https://basecamp.com/{MyCompanyID}/api/v1/attachments.json`) with the file you want to be the attachment as the request body, the `Content-Type` would be the MIME type that corresponds to your file ([this list](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types) might be handy!) 
and `Content-Length` should be the size of your file. If this is successful, you'll get the token you need back as response.

2. Once you have the token, you can _attach_ the file you just uploaded to an element: comment, message, to-do, or upload. In the API docs for each of those elements you can find how to do so. For example, suppose you want simply to [attach it to an upload](https://github.com/basecamp/bcx-api/blob/master/sections/uploads.md#create-uploads). You need to do a `POST` request to `/projects/{MyProjectID}/uploads.json`, using the token from step 1 when building the request body. 

Is ARC the Advanced Rest Client extension for Chrome? If that's the case, I think I may know what you are struggling with. I tested it and I couldn't find a way to add the file binary data as request body. When trying to upload a file with this extension, it always sends it as a form parameter, and automatically sets the `Content-Type` to `multipart/form-data`. That's not going to work. 

I can suggest a different tool, though, that you might find useful, and also works as a Chrome app: [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en). With that one you shouldn't have any issues sending the file as request body. Other kind of requests work very similarly as Advanced Rest Client. 

Let me know if you have other questions!

**Comment by GaryLBaird** [comment]
When I attempt to post I get the following return:
```
Abort / timeout

The request has been aborted manually or because of the connection timeout. There were no response from the server but the connection wasn't closed.

You can adjust timeout in settings.

Try to:

add "Connection: close" header which should be used by the server to close the connection after it finish generating response
Please, check if:

all required services (like www) are up and running on server
method is correct
port number is correct
url is correct
all required headers and/or payload has been added to the request
Example

Sometimes it may happen when you use http protocol instead of https. Also it may happen when you use different URL (port / protocol) and the server is not configured properly.
```
My Settings below. I attached a zip file and tried the following. It needs to go to a specific project so I think I am missing something here.
Post:
https://basecamp.com/{MyCompanyID}/api/v1/attachments.json
accept: application/json
authorization: Basic (MyBase64)
Content-Type: application/zip
Content-Length: 2987299

**Comment by rosa** [comment]
@GaryLBaird you aren't missing anything 😃 You'll associate the attachment with an element within a specific project in the second step. I think that error you are getting might be coming from your REST client... Are you still using ARC? If so, I found out [this workaround](https://marcustalcott.com/2016/11/03/error-making-a-rest-call/?iframe=true&theme_preview=true) from someone using ARC as well, and getting the same timeout error. Short answer: toggle the `Use XHR` button. It sounds strange, but if you have any other timeout setting in your REST client that you can increase, you can try that as well.

**Comment by GaryLBaird** [comment]
Yes I have been using ARC to test before I did the coding. I am sure that will help me.

**Comment by GaryLBaird** [comment]
You were right it worked! It was necessary to enable the XHR command.

**Comment by GaryLBaird** [comment]
Now the next step is to upload and that feature is also having difficulties. Is there an example of using this using curl?
I am not sure how to add this content: 
Using ARC it just hangs with the following settings;
https://basecamp.com/{CompanyID}/api/v1/?POST=/projects/{ProjectID}/uploads.json
accept: application/json
authorization: Basic {MyBase64}
User-Agent: {MyEmailUser}
I'm not sure where this content goes either:
```
{
  "content": "Here's the new logo!",
  "attachments": [
    {
      "token": "4f71ea23-134660425d1818169ecfdbaa43cfc07f4e33ef4c",
      "name": "new_logo.png"
    }
  ],
  "subscribers": [1, 5, 6]
}
```

**Comment by rosa** [comment]
@GaryLBaird the URL you are using is wrong, you don't need the `?POST=` part. It should be:
`https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads.json`. The content of the upload should be the request body, which goes with a `Content-Type: application/json` header. I hope this helps!

**Comment by GaryLBaird** [comment]
It still doesn't seem to work. I run the attachments.json and it returns a token. Then I run the uploads.json and the file never seems to show up. Both return the code 200, meaning it was a success.

returns = RestClient.post url, {payload: path}.to_json, {'accept': 'application/json', 'authorization': auth, 'user-agent': user_agent, 'subscribers': subscribers, 'content_type': 'application/zip', 'name': comp}
Gets return code 200
returns: 
{"response"=>200, "token"=>"81fe5afe-6334-11e7-94a8-00266cfb8f40", "name"=>"test_logs_20170630-20170701.zip"}

https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads.json
I pass the token in a post and it also gets a return code 200, but when I check the file is not uploaded and when I look at the attachments:
https://basecamp.com/{CompanyID}/api/v1/attachments.json
Unexpected Results:
The number of attachments never changes. No new attachments at all.

**Comment by GaryLBaird** [comment]
I'm wondering if this feature was never tested with basecamp. I am fairly sure it doesn't work no matter how or what I do, but the message response is 200 saying it was successful.

**Comment by GaryLBaird** [comment]
Any update on this status yet?

I have spent a lot of time working on API's over the past week and I think I understand them fairly well now. Is there any way someone can test an upload and see if it is actually working?

**Comment by rosa** [comment]
Hey @GaryLBaird, sorry for the delay! I just tested it and can confirm that this is working fine. The response to the `POST /uploads.json` should be `201 Created` if the creation of the new upload with the attachment was successful, and the response body will contain a representation of the new upload created, something like the response you get to the `GET /upload` endpoint [here](https://github.com/basecamp/bcx-api/blob/master/sections/uploads.md#get-upload). If you aren't getting that, there must be something wrong with your request. At first look, this code here:
```
RestClient.post( @basecamp_upload_url, 'body', 'accept': 'application/json', 'authorization': @auth, 'user-agent': @user_agent, 'User-Agent': 'firefox', 'content': { 'attachments': { 'name': @comp, 'token': "#{@token}" } } )
```
looks a bit strange. What is `'body'` supposed to be? Why do you have `user-agent` duplicated? The `Content-Type` is not set. Is it set to `application/json` by default? And are the `'content': { 'attachments': { 'name': @comp, 'token': "#{@token}" }` parameters converted to JSON automatically by your `RestClient`?

**Comment by GaryLBaird** [comment]
Maybe you can attach a piece of source code to look at.

**Comment by rosa** [comment]
Here you have an example of a successful request using `curl`: 
```
curl -X POST \
  https://basecamp.com/000000/api/v1/projects/0000000/uploads.json \
  -H 'authorization: Basic $TOKEN' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
  "content": "Here'\''s the new logo!",
  "attachments": [
    {
      "token": "08b6fcbc-6d1d-1111-aaee-00266cfccb5c",
      "name": "new_logo.png"
    }
  ],
  "subscribers": []
}'
```
It should be possible to convert this to any language you want to use following its documentation.

**Comment by GaryLBaird** [comment]
Yes I have tried it, but the example doesn't generate the token. I get a token back but when I look at the uploads table the token doesn't show up. The biggest problem is the upload.

**Comment by jeremy** [comment]
@GaryLBaird From here, it's a matter of implementation work and debugging!

If you're hitting issues with ARC or other tools, please verify that you can get things working using `curl` alone. That's a great way to rule out external factors and makes it easy to follow along with the official docs.

Once you have the flow working, start implementing in the language and tools of your choice. Since you'll be incrementally translating a working example, any issues you hit should pop out straightaway.

**Comment by GaryLBaird** [comment]
I was able to get curl working, but example provided is missing the -H "accept: application/json" and missing quotes around the file name and location i.e. -u "@/filename". Please update the curl example from https://github.com/basecamp/bcx-api/blob/master/sections/attachments.md.

Also in Windows using curl you for some reason may have switch from single quotes to double quotes. 

Working Curl Example:
curl --data-binary "@c:\zipfile.zip" \
       -u "david@basecamp.com:pass" \
       -H "Content-Type: application/zip" \
       -H "User-Agent: david@basecamp.com" \
       -H "accept: application/json" \
       https://basecamp.com/999999999/api/v1/attachments.json
