### ISSUE TITLE
Project Attachments API getting status 404 not found

### ISSUE THREAD

**Issue by GaryLBaird** [basecamp/bcx-api#218]
Project Attachments API getting status 404 not found when applying to specific project, but all projects seems to work.
https://www.basecamp.com/{CompanyID}/api/v1/GET=/projects/{ProjectID}/attachments/1.json 
accept: application/json
authorization: Basic {base64 user:pass}
User-Agent: {Username}@{DomainName}.{Domain}

**Unexpected Results:**
```
{
"status": "404",
"error": "Not Found"
}
```
I can search out all attachments for all projects like this just fine:
https://basecamp.com/{CompanyID}/api/v1/attachments.json

Gives expected results:

`[
  {
"id": {FileID1},
"name": "{FileName1}",
"byte_size": 928498,
"content_type": "application/zip",
"created_at": "2017-07-05T12:10:19.000-06:00",
"updated_at": "2017-07-05T12:10:45.000-06:00",
"private": false,
"trashed": false,
"key": "2a40e1fc-61ad-11e7-9830-e89a8fb23f02",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID1}/2a40e1fc-61ad-11e7-9830-e89a8fb23f02/original/{FileName1}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID1}/2a40e1fc-61ad-11e7-9830-e89a8fb23f02/original/{FileName1}",
"tags": [
  "20170702-20170507 logs zip file"
],
"creator": {
"id": {CreatorID1},
"name": "{UserName}",
"avatar_url": "http://cdn.37img.com/global/8b9d1895961eeee17aa452a84cc1bdf50010/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/global/8b9d1895961eeee17aa452a84cc1bdf50010/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": {AttachementID1},
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/{AttachementID1}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/{AttachementID1}"
}
},
  {
"id": {FileID2},
"name": "{FileName2}",
"byte_size": 2987299,
"content_type": "application/zip",
"created_at": "2017-07-01T11:06:41.000-06:00",
"updated_at": "2017-07-03T06:27:33.000-06:00",
"private": false,
"trashed": false,
"key": "92c1a9f4-5e7f-11e7-a53d-089e019fd4bb",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID2}/92c1a9f4-5e7f-11e7-a53d-089e019fd4bb/original/{FileName2}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID2}/92c1a9f4-5e7f-11e7-a53d-089e019fd4bb/original/{FileName2}",
"tags": [],
"creator": {
"id": {CreatorID2},
"name": "{UserName}",
"avatar_url": "http://cdn.37img.com/global/8b9d1895961eeee17aa452a84cc1bdf50010/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/global/8b9d1895961eeee17aa452a84cc1bdf50010/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID2},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": {AttachableID2},
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/{AttachableID2}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/{AttachableID2}"
}
},
  {
"id": {FileID3},
"name": "{FileName3}",
"byte_size": 299704,
"content_type": "application/octet-stream",
"created_at": "2017-06-30T11:47:53.000-06:00",
"updated_at": "2017-06-30T11:47:53.000-06:00",
"private": false,
"trashed": false,
"key": "3d4ed87a-5dbc-11e7-b984-008cfa092f90",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID3}/3d4ed87a-5dbc-11e7-b984-008cfa092f90/original/{FileName3}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID3}/3d4ed87a-5dbc-11e7-b984-008cfa092f90/original/{FileName3}",
"tags": [],
"creator": {
"id": {creatorID3},
"name": "{UserName3}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_9/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_9/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectIDID3},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": {AttachableID3},
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/{AttachableID3}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/{AttachableID3}"
}
},
  {
"id": {FileID4},
"name": "{FileName4}",
"byte_size": 2275076,
"content_type": "application/zip",
"created_at": "2017-06-30T08:25:54.000-06:00",
"updated_at": "2017-06-30T08:25:54.000-06:00",
"private": false,
"trashed": false,
"key": "faf6906a-5d9f-11e7-85e1-e89a8f741044",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID4}/faf6906a-5d9f-11e7-85e1-e89a8f741044/original/{FileName4}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID4}/faf6906a-5d9f-11e7-85e1-e89a8f741044/original/{FileName4}",
"tags": [],
"creator": {
"id": {creatorID4},
"name": "{UserName4}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_2/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_2/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID4},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": {attachableID4},
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/{attachableID4}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/{attachableID4}"
}
},
  {
"id": {FileID5},
"name": "{FileName5}",
"byte_size": 3792,
"content_type": "text/plain",
"created_at": "2017-06-29T11:01:25.000-06:00",
"updated_at": "2017-06-29T11:01:25.000-06:00",
"private": false,
"trashed": false,
"key": "946ca702-5cec-11e7-aac7-e89a8fbdc1de",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID5}/946ca702-5cec-11e7-aac7-e89a8fbdc1de/original/{FileName5}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID5}/946ca702-5cec-11e7-aac7-e89a8fbdc1de/original/{FileName5}",
"tags": [],
"creator": {
"id": 14139748,
"name": "{UserName5}",
"avatar_url": "http://cdn.37img.com/global/fd57ffb63c5254f7b321834e446612b90010/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/global/fd57ffb63c5254f7b321834e446612b90010/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 38311640,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/38311640.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/38311640"
}
},
  {
"id": {FileID6},
"name": "{FileName6}",
"byte_size": 4877678,
"content_type": "application/zip",
"created_at": "2017-06-29T10:35:12.000-06:00",
"updated_at": "2017-06-29T10:35:12.000-06:00",
"private": false,
"trashed": false,
"key": "e9070e78-5ce8-11e7-9cc5-e89a8fbdc1e0",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID6}/e9070e78-5ce8-11e7-9cc5-e89a8fbdc1e0/original/{FileName6}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID6}/e9070e78-5ce8-11e7-9cc5-e89a8fbdc1e0/original/{FileName6}",
"tags": [],
"creator": {
"id": 14139748,
"name": "{UserName6}",
"avatar_url": "http://cdn.37img.com/global/fd57ffb63c5254f7b321834e446612b90010/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/global/fd57ffb63c5254f7b321834e446612b90010/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 38311079,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/38311079.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/38311079"
}
},
  {
"id": {FileID7},
"name": "{FileName7}",
"byte_size": 22420,
"content_type": "application/xml",
"created_at": "2017-06-28T16:29:05.000-06:00",
"updated_at": "2017-06-28T16:29:05.000-06:00",
"private": false,
"trashed": false,
"key": "2fc73f10-5c51-11e7-9786-e89a8fbdc254",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID7}/2fc73f10-5c51-11e7-9786-e89a8fbdc254/original/{FileName7}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID7}/2fc73f10-5c51-11e7-9786-e89a8fbdc254/original/{FileName7}",
"tags": [],
"creator": {
"id": 15055543,
"name": "{UserName7}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_3/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_3/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 38301917,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/38301917.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/38301917"
}
},
  {
"id": {FileID8},
"name": "{FileName8}",
"byte_size": 2118146,
"content_type": "application/zip",
"created_at": "2017-06-28T15:15:34.000-06:00",
"updated_at": "2017-06-28T15:15:34.000-06:00",
"private": false,
"trashed": false,
"key": "e80afe00-5c46-11e7-b247-e89a8f741358",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID8}/e80afe00-5c46-11e7-b247-e89a8f741358/original/{FileName8}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID8}/e80afe00-5c46-11e7-b247-e89a8f741358/original/{FileName8}",
"tags": [],
"creator": {
"id": 15055543,
"name": "{UserName8}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_3/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_3/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 38299588,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/38299588.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/38299588"
}
},
  {
"id": {FileID9},
"name": "{FileName9}",
"byte_size": 6736180,
"content_type": "application/zip",
"created_at": "2017-06-05T07:04:14.000-06:00",
"updated_at": "2017-06-05T07:04:14.000-06:00",
"private": false,
"trashed": false,
"key": "2aa2f3bd29b386cb74e458f45297a5080010",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID9}/2aa2f3bd29b386cb74e458f45297a5080010/original/{FileName9}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID9}/2aa2f3bd29b386cb74e458f45297a5080010/original/{FileName9}",
"tags": [],
"creator": {
"id": 14139748,
"name": "{UserName9}",
"avatar_url": "http://cdn.37img.com/global/fd57ffb63c5254f7b321834e446612b90010/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/global/fd57ffb63c5254f7b321834e446612b90010/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 37962770,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/37962770.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/37962770"
}
},
  {
"id": {FileID10},
"name": "{FileName10}",
"byte_size": 1427985,
"content_type": "application/zip",
"created_at": "2017-06-01T14:27:18.000-06:00",
"updated_at": "2017-06-02T06:53:38.000-06:00",
"private": false,
"trashed": false,
"key": "be3b74d52351d9940ff058bacd0dcafe0010",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID10}/be3b74d52351d9940ff058bacd0dcafe0010/original/{FileName10}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID10}/be3b74d52351d9940ff058bacd0dcafe0010/original/{FileName10}",
"tags": [],
"creator": {
"id": 15055543,
"name": "{UserName10}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_3/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_3/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 37931220,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/37931220.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/37931220"
}
},
  {
"id": {FileID11},
"name": "{FileName11}",
"byte_size": 154536,
"content_type": "application/octet-stream",
"created_at": "2017-05-25T10:54:57.000-06:00",
"updated_at": "2017-05-25T10:54:57.000-06:00",
"private": false,
"trashed": false,
"key": "986d6361770f61ec2ac8fad89a7cdd510010",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID11}/986d6361770f61ec2ac8fad89a7cdd510010/original/{FileName11}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID11}/986d6361770f61ec2ac8fad89a7cdd510010/original/{FileName11}",
"tags": [
  "LogFiles_05.25.2017"
],
"creator": {
"id": 15055543,
"name": "{UserName11}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_3/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_3/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 37842020,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/37842020.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/37842020"
}
},
  {
"id": {FileID12},
"name": "{FileName12}",
"byte_size": 8946821,
"content_type": "application/zip",
"created_at": "2017-05-24T14:35:32.000-06:00",
"updated_at": "2017-05-24T14:35:32.000-06:00",
"private": false,
"trashed": false,
"key": "6c3f7735149048895383a41868def52a0010",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID12}/6c3f7735149048895383a41868def52a0010/original/{FileName12}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID12}/6c3f7735149048895383a41868def52a0010/original/{FileName12}",
"tags": [],
"creator": {
"id": 13475289,
"name": "{UserName12}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_9/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_9/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}"
},
"attachable": {
"id": 37829707,
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/37829707.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/37829707"
}
},
  {
"id": {FileID13},
"name": "{FileName13}",
"byte_size": 37960920,
"content_type": "application/x-msdos-program",
"created_at": "2017-05-24T14:35:19.000-06:00",
"updated_at": "2017-05-24T14:35:19.000-06:00",
"private": false,
"trashed": false,
"key": "ec3f6f544c8ceb50566ea80de4128e070010",
"url": "https://asset1.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{FileID13}/ec3f6f544c8ceb50566ea80de4128e070010/original/{FileName13}",
"app_url": "https://asset1.basecamp.com/{CompanyID}/projects/{ProjectID}/attachments/{FileID13}/ec3f6f544c8ceb50566ea80de4128e070010/original/{FileName13}",
"tags": [],
"creator": {
"id": 13475289,
"name": "{UserName13}",
"avatar_url": "http://cdn.37img.com/builtin/default_avatar_v1_9/avatar.gif?r=3",
"fullsize_avatar_url": "https://cdn.37img.com/builtin/default_avatar_v1_9/original.gif?r=3"
},
"bucket": {
"type": "Project",
"id": {ProjectID13},
"name": "Top of Mind: {ProjectName}",
"color": "e207c1",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID13}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID13}"
},
"attachable": {
"id": {attachable13},
"type": "Upload",
"url": "https://basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/uploads/{attachable13}.json",
"app_url": "https://basecamp.com/{CompanyID}/projects/{ProjectID}/uploads/{attachable13}"
}
}
],`

**Comment by rosa** [comment]
Hey @GaryLBaird, it looks like the URL you are using is wrong, that's why it's not found. It should be `https://www.basecamp.com/{CompanyID}/api/v1/projects/{ProjectID}/attachments/{AttachmentID}.json`, without the extra `GET=` part. Also, the last `1` in the URL should be replaced with the attachment id you want to fetch (`{FileID1}`, `{FileID2}`, etc, in your example response). I hope this helps!
