### ISSUE TITLE
Unable to make ajax request

### ISSUE THREAD

**Issue by dcp3450** [basecamp/bcx-api#220]
I'm using the Basecamp 2 api to request data via a ReactJS app. A standard ajax request returns a crossdomain error (as expected) however, a jsonp request returns and error, " MIME type ('application/json') is not executable, and strict MIME type checking is enabled."

**Comment by jeremy** [comment]
Hey @dcp3450— Basecamp 2 doesn't offer a cross-origin JavaScript API. Your best bet is to proxy API requests via your own server.
