### ISSUE TITLE
Event Polling Recommendations

### ISSUE THREAD

**Issue by mwbrooks** [basecamp/bcx-api#221]
Hi there,

I have an integration that's polling events and I'd like to just make sure that I'm not abusing your API.

- I use the [`since=` parameter](https://github.com/basecamp/bcx-api/blob/master/sections/events.md#events) to reduce the event API responses.
- I follow the [rate limiting guidelines](https://github.com/basecamp/bcx-api#rate-limiting) for error handling and throttling.

The [rate limiting guidelines](https://github.com/basecamp/bcx-api#rate-limiting) states:
> You can perform up to 500 requests per 10 second period from the same IP address for the same account. 

Is the "account" the 37signals Basecamp integration or the authorized user's Basecamp account?

Thanks!
Michael

**Comment by jeremy** [comment]
You're all set, @mwbrooks! The "account" is per authorized user, not the integration itself.

**Comment by mwbrooks** [comment]
Cool, sounds good to me. Thanks as well @jeremy for responding so quickly!
