### ISSUE TITLE
Pagination documentation should have an working example

### ISSUE THREAD

**Issue by PatrickGrub** [basecamp/bcx-api#223]
The current documentation [here for pagination](https://github.com/basecamp/bcx-api#pagination) describes to use "more results by adding &page=2" but this will not work!

Instead, you have to use **?** instead of **&** to get it working.

Already mentioned here somehow: https://github.com/basecamp/bcx-api/issues/81

Thanks,
Patrick

**Comment by rosa** [comment]
@PatrickGrub yes, you are right. The example assumes you might have other query parameters in the URL already, so you'd need to add `&page=2`, `&page=3`, etc. I'll explain this better in the docs.
