### ISSUE TITLE
Attachments endpoint to download original is returning a redirect (as an HTML response)

### ISSUE THREAD

**Issue by justinperkins** [basecamp/bcx-api#225]
From this API endpoint: https://github.com/basecamp/bcx-api/blob/master/sections/attachments.md

Each attachment has a "url" value, when that value is requested (with correct authorization headers), instead of returning the original raw asset, it returns an HTML response with a redirect to "https://storage.googleapis.com ...". This is a change from previous behavior and also looks to be undocumented either way what the "url" value of an attachment is expected to do. At least according to the API doc page that I'm reading.

As an API consumer, what is the recommended course of action here? Is there any announcements about breaking API changes like this? I'm not sure when it occurred but is obvious that as of now, our product is failing to ingest Basecamp attachments due to this behavior.

Note: The URL in the redirect can be followed and with the correct authorization, will return the original raw asset.

**Comment by rosa** [comment]
Hey @justinperkins! Sorry for encountering this change and that it broke your integration. This has been like this for more than one year, in BCX's API and also BC3's API. We sent an email to all people who had an integration using the BC3 API but we failed to do the same with BCX integrators, I'm really sorry about this. It certainly won't happen again, it's very unlikely we do any breaking changes to BCX's API, but if we did, we'll make sure to notify everyone involved with plenty of time in advance.  

For now on, please ensure that your integration follows `302 Found` redirects when downloading attachments. Further ensure that it does not send `Authorization` headers intended for Basecamp to a third party when following redirects.

**Comment by justinperkins** [comment]
Thanks so much @rosa and good call on ensuring the auth headers don't carry over. I switched our HTTP library to one that auto-follows redirects but I will do some logging to see what is being sent on redirect follow.

I guess we found out that not many people use this particular integration :(
