### ISSUE TITLE
OAuth2 Bad Request expired_verification_code

### ISSUE THREAD

**Issue by 8bit-echo** [basecamp/bcx-api#226]
I am able to successfully get an authorization code from my app, but whenever I attempt to trade my authentication code for a token, I always get a response code 400 with the message “expired_verification_code”, despite making the request for the token immediately after hitting the redirect uri. 

I know that there must be some user error involved here, because I don’t have an issue when testing this flow with Postman. Can you help me understand what’s causing my app to throw this error? 

Here’s a quick outline of the process: 
-User initiates request to BCX.
-User clicks “allow access”
-App successfully grabs auth code from query string in the redirect window.
-App sends POST request to token url including the new auth code.
-BCX returns response to app with error message above.

**Comment by rosa** [comment]
Huh, are you getting a `X-Request-Id` header back on the last step? If you are, could you let us know the value? We can use that to track down the request and know what's exactly happening for us to return that error.

**Comment by 8bit-echo** [comment]
Yes, here's my request ID.

`'x-request-id': [ 'a93495b9-7943-4d4a-9cd9-8b992cb8d481' ]`

**Comment by rosa** [comment]
Thank you! I had a look and saw you're sending a 7-char code which we can't find. Codes have 8 characters. Maybe you're somehow truncating it when grabbing it from the query string?

**Comment by 8bit-echo** [comment]
Yes, that was it! Thank you so much for your help.

**Comment by rosa** [comment]
Great! Really glad that helped! 👏
