### ISSUE TITLE
Topics within a specific date/time range

### ISSUE THREAD

**Issue by akshayklr057** [basecamp/bcx-api#230]
Hi team,
Is there a way to get topics based on a specific date/time range. For example, if I want to extract all three for past one day only, is there a way to do that? 
While exploring the API, I see that the response gives you "created_at" & "updated_at" times but I was not able to find if we can get responses based on time/date.

**Comment by rosa** [comment]
Hey @akshayklr057! You're right, it's not possible to retrieve topics using a specific date/time range. We don't have plans to implement this, I'm sorry!
