### ISSUE TITLE
Show all to do's with no one assigned

### ISSUE THREAD

**Issue by techguychad** [basecamp/bcx-api#231]
Is there any way to get a list of all To do's with no one assigned using the API?  I am new to GitHub so bear with me.

**Comment by rosa** [comment]
Hi @techguychad! No, sorry. You'd have to do this manually, fetching all to-dos via the [Get to-dos endpoint](https://github.com/basecamp/bcx-api/blob/master/sections/todos.md#get-to-dos) and filtering the ones without `assignee`.
