### ISSUE TITLE
Filtering the requested calendar events based on date

### ISSUE THREAD

**Issue by rvanbaalen** [basecamp/bcx-api#232]
When using the calendar_events.json endpoint, I noted there is a, much needed, `start_date` parameter. 
Some of the users of my application have calendar events dating back multiple years so I wanted to use this parameter to only retrieve calendar events from up to a year ago.

Much to my surprise, I discovered that when using the `start_date` parameter, the output is limited to 6 weeks of calendar events.

How can I retrieve all calendar events from up to a year ago? I don't want to make all the API calls for the entire dataset and filter on my end, that seems counter productive. Are there more options to request calendar events from a predefined set of dates (e.g. starting a year ago until next year, for instance).

**Comment by jeremy** [comment]
Hey @rvanbaalen, good catch! Indeed there is a six-week default window. You can pass `end_date` along with `start_date` to get the full range, ensuring you paginate the results.

**Comment by rvanbaalen** [comment]
Hi Jeremy. Thank you for your reply. The documentation states that there'll always be a six week window between start and end date. That is not correct? If so, I'll just have to use both parameters to retrieve all events for the past year (using pagination).

**Comment by jeremy** [comment]
From reading the code, I think the docs are incorrect, @rvanbaalen. Could you give it a try and report back?
